# Generated by Django 4.2.16 on 2024-09-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Profesor', models.CharField(max_length=35)),
                ('Codigo_Seccion', models.CharField(max_length=25)),
                ('Nombres', models.CharField(max_length=80)),
                ('Apellidos', models.CharField(max_length=80)),
                ('Modalidad', models.CharField(max_length=50)),
                ('Sexo', models.CharField(max_length=15)),
                ('Cedula', models.CharField(max_length=50)),
            ],
        ),
    ]
