# Generated by Django 4.2.16 on 2024-09-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Matricula', models.CharField(max_length=35)),
                ('Grado', models.CharField(max_length=25)),
                ('Fecha_Matricula', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
