# Generated by Django 4.2.16 on 2024-09-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoNota', models.CharField(max_length=35)),
                ('HoraInicio', models.CharField(max_length=50)),
                ('CodigoEstudiante', models.CharField(max_length=35)),
                ('NombreEstudainte', models.CharField(max_length=35)),
                ('ApellidoEstudiante', models.CharField(max_length=35)),
                ('Modalidad', models.CharField(max_length=35)),
                ('Grado', models.CharField(max_length=35)),
                ('Materia', models.CharField(max_length=35)),
                ('Seccion', models.CharField(max_length=35)),
                ('PrimerCorte', models.CharField(max_length=35)),
                ('SegundoCorte', models.CharField(max_length=35)),
                ('TercerCorte', models.CharField(max_length=35)),
                ('CuartoCorte', models.CharField(max_length=35)),
                ('PrimerSemestre', models.CharField(max_length=35)),
                ('SegundoSemestre', models.CharField(max_length=35)),
                ('TotalNotas', models.CharField(max_length=50)),
            ],
        ),
    ]
