# Generated by Django 4.2.16 on 2024-09-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.CharField(max_length=50)),
                ('Nombre1', models.CharField(max_length=50)),
                ('Nombre2', models.CharField(max_length=50)),
                ('Apellido1', models.CharField(max_length=50)),
                ('Apellido2', models.CharField(max_length=50)),
                ('Centro_de_Trabajo', models.CharField(max_length=85)),
                ('Telefono', models.CharField(max_length=12)),
                ('Correo_Electronico', models.CharField(max_length=75)),
            ],
        ),
    ]
