# Generated by Django 4.2.16 on 2024-09-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoOcupacion', models.CharField(max_length=30)),
                ('NombreOcupacion', models.CharField(max_length=60)),
                ('Salario', models.CharField(max_length=20)),
            ],
        ),
    ]
