# Generated by Django 4.2.16 on 2024-09-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoOferta', models.CharField(max_length=35)),
                ('Grupo', models.CharField(max_length=25)),
                ('Aula', models.CharField(max_length=16)),
                ('AnoElectivo', models.CharField(max_length=60)),
                ('HoraInicial', models.CharField(max_length=10)),
                ('HoraFinal', models.CharField(max_length=10)),
            ],
        ),
    ]
