# Generated by Django 4.2.16 on 2024-09-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Departamento', models.CharField(max_length=35)),
                ('Nombre_Departamento', models.CharField(max_length=60)),
            ],
        ),
    ]
