# Generated by Django 4.2.16 on 2024-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Estudiante', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=75)),
                ('Apellidos', models.CharField(max_length=75)),
                ('Sexo', models.CharField(max_length=15)),
                ('Fecha_Nacimiento', models.CharField(max_length=15)),
            ],
        ),
    ]
